# These are supported funding model platforms

github: #  UTKA Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # UTKA  Replace with a single Patreon username
open_collective: # UTKA Replace with a single Open Collective username UTKA
ko_fi: # UTKA  Replace with a single Ko-fi username
tidelift: # UTKA  Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # UTKA Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # UTKA Replace with a single IssueHunt username
otechie: # UTKA Replace with a single Otechie username
lfx_crowdfunding: # UTKA Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # UTKA Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
